In [1]:
import numpy as np
import pandas as pd

###### Read the csv file using pandas

In [48]:
data_file_pd=pd.read_csv("PL17_18.csv")

###### An over view of the data the first 5 columns

In [35]:
data_file_pd.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,11/08/2017,Arsenal,Leicester,4,3,H,2,2,D,...,2.32,21,-1.00,1.91,1.85,2.10,2.02,1.49,4.73,7.25
1,E0,12/08/2017,Brighton,Man City,0,2,A,0,0,D,...,2.27,20,1.50,1.95,1.91,2.01,1.96,11.75,6.15,1.29
2,E0,12/08/2017,Chelsea,Burnley,2,3,A,0,3,A,...,2.23,20,-1.75,2.03,1.97,1.95,1.90,1.33,5.40,12.25
3,E0,12/08/2017,Crystal Palace,Huddersfield,0,3,A,0,2,A,...,1.72,18,-0.75,2.10,2.05,1.86,1.83,1.79,3.56,5.51
4,E0,12/08/2017,Everton,Stoke,1,0,H,1,0,H,...,1.76,19,-0.75,1.94,1.90,2.01,1.98,1.82,3.49,5.42

###### iloc : integer location

In [36]:
data_file_pd.iloc[0] #iloc : integer location

Div                 E0
Date        11/08/2017
HomeTeam       Arsenal
AwayTeam     Leicester
FTHG                 4
               ...
BbMxAHA            2.1
BbAvAHA           2.02
PSCH              1.49
PSCD              4.73
PSCA              7.25
Name: 0, Length: 65, dtype: object

###### All the games played by liverpool 18/19 season

In [37]:
c=data_file_pd.loc[(data_file_pd["HomeTeam"]=="Liverpool") | (data_file_pd["AwayTeam"]=="Liverpool")]
data_file_pd.loc[(data_file_pd["HomeTeam"]=="Liverpool") | (data_file_pd["AwayTeam"]=="Liverpool")]

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
6,E0,12/08/2017,Watford,Liverpool,3,3,D,2,1,H,...,1.99,21,1.00,1.90,1.84,2.13,2.04,6.88,4.27,1.56
13,E0,19/08/2017,Liverpool,Crystal Palace,1,0,H,0,0,D,...,2.40,17,-1.50,2.14,2.07,1.85,1.82,1.39,5.31,9.00
27,E0,27/08/2017,Liverpool,Arsenal,4,0,H,2,0,H,...,2.38,16,-0.25,1.89,1.86,2.07,2.03,2.21,3.67,3.25
34,E0,09/09/2017,Man City,Liverpool,5,0,H,2,0,H,...,2.51,15,-0.50,1.90,1.87,2.05,2.02,1.89,3.98,4.14
43,E0,16/09/2017,Liverpool,Burnley,1,1,D,1,1,D,...,2.44,15,-1.75,2.01,1.94,1.99,1.92,1.26,6.60,13.00
52,E0,23/09/2017,Leicester,Liverpool,2,3,A,1,2,A,...,2.18,17,0.75,1.82,1.78,2.16,2.11,4.40,4.18,1.81
69,E0,01/10/2017,Newcastle,Liverpool,1,1,D,1,1,D,...,2.18,17,0.75,2.01,1.96,1.95,1.91,5.02,4.14,1.72
72,E0,14/10/2017,Liverpool,Man United,0,0,D,0,0,D,...,1.91,17,0.00,1.98,1.93,1.98,1.94,2.75,3.29,2.82
89,E0,22/10/2017,Tottenham,Liverpool,4,1,H,3,1,H,...,2.23,20,-0.25,1.93,1.88,2.03,1.99,2.24,3.62,3.36
93,E0,28/10/2017,Liverpool,Huddersfield,3,0,H,0,0,D,...,2.61,20,-2.00,2.26,2.16,1.79,1.73,1.25,6.70,14.00
105,E0,04/11/2017,West Ham,Liverpool,1,4,A,0,2,A,...,2.28,20,1.00,1.84,1.79,2.16,2.08,6.29,4.68,1.54
115,E0,18/11/2017,Liverpool,Southampton,3,0,H,2,0,H,...,2.24,19,-1.25,1.92,1.87,2.05,2.00,1.42,5.07,8.47
122,E0,25/11/2017,Liverpool,Chelsea,1,1,D,0,0,D,...,2.17,19,-0.25,1.86,1.83,2.11,2.06,2.21,3.59,3.45
139,E0,29/11/2017,Stoke,Liverpool,0,3,A,0,1,A,...,2.38,19,1.00,2.07,2.02,1.88,1.85,6.21,4.58,1.56
141,E0,02/12/2017,Brighton,Liverpool,1,5,A,0,2,A,...,2.05,20,1.00,2.13,2.09,1.84,1.80,7.25,4.39,1.53
157,E0,10/12/2017,Liverpool,Everton,1,1,D,1,0,H,...,2.62,23,-1.75,2.05,1.99,1.91,1.86,1.37,5.25,9.95
163,E0,13/12/2017,Liverpool,West Brom,0,0,D,0,0,D,...,2.53,24,-2.00,2.12,2.05,1.85,1.81,1.21,7.80,15.75
177,E0,17/12/2017,Bournemouth,Liverpool,0,4,A,0,3,A,...,2.41,21,1.00,2.13,2.08,1.84,1.80,7.35,5.25,1.44
180,E0,22/12/2017,Arsenal,Liverpool,3,3,D,0,1,A,...,2.57,19,-0.25,2.20,2.13,1.82,1.76,2.68,3.69,2.66
193,E0,26/12/2017,Liverpool,Swansea,5,0,H,1,0,H,...,2.92,20,-2.25,2.02,1.97,1.95,1.90,1.14,10.50,21.00
203,E0,30/12/2017,Liverpool,Leicester,2,1,H,0,1,A,...,2.93,20,-1.75,2.11,2.03,1.87,1.83,1.27,7.10,11.00
210,E0,01/01/2018,Burnley,Liverpool,1,2,A,0,0,D,...,2.02,20,1.00,2.08,2.04,1.87,1.82,6.60,3.80,1.65
228,E0,14/01/2018,Liverpool,Man City,4,3,H,1,1,D,...,2.51,19,0.25,1.90,1.87,2.06,1.99,3.22,3.62,2.31
239,E0,22/01/2018,Swansea,Liverpool,1,0,H,1,0,H,...,2.21,19,1.50,2.00,1.95,1.98,1.92,11.68,5.87,1.31
240,E0,30/01/2018,Huddersfield,Liverpool,0,3,A,0,2,A,...,2.20,20,1.50,2.02,1.96,1.95,1.90,10.95,5.49,1.34
258,E0,04/02/2018,Liverpool,Tottenham,2,2,D,1,0,H,...,2.36,19,-0.25,1.85,1.79,2.14,2.07,2.01,3.84,3.81
268,E0,11/02/2018,Southampton,Liverpool,0,2,A,0,2,A,...,2.18,21,0.75,1.91,1.86,2.06,2.00,5.18,4.05,1.72
274,E0,24/02/2018,Liverpool,West Ham,4,1,H,1,0,H,...,2.79,21,-1.75,1.86,1.81,2.13,2.06,1.24,7.00,14.00
282,E0,03/03/2018,Liverpool,Newcastle,2,0,H,1,0,H,...,2.86,22,-2.00,2.04,1.96,1.97,1.90,1.20,7.80,16.00
293,E0,10/03/2018,Man United,Liverpool,2,1,H,2,0,H,...,1.92,19,-0.25,2.38,2.31,1.70,1.65,3.20,3.26,2.49
302,E0,17/03/2018,Liverpool,Watford,5,0,H,2,0,H,...,2.89,22,-2.00,1.90,1.84,2.11,2.03,1.17,9.00,18.45
305,E0,31/03/2018,Crystal Palace,Liverpool,1,2,A,1,0,H,...,2.40,19,1.25,1.90,1.78,2.20,2.11,7.00,4.70,1.51
316,E0,07/04/2018,Everton,Liverpool,0,0,D,0,0,D,...,1.97,18,0.75,1.77,1.73,2.25,2.18,3.78,3.39,2.17
327,E0,14/04/2018,Liverpool,Bournemouth,3,0,H,1,0,H,...,3.02,19,-1.75,1.86,1.80,2.15,2.08,1.24,7.30,13.50
339,E0,21/04/2018,West Brom,Liverpool,2,2,D,0,1,A,...,2.01,22,1.00,2.09,2.04,1.95,1.83,6.55,4.13,1.60
347,E0,28/04/2018,Liverpool,Stoke,0,0,D,0,0,D,...,2.53,21,-1.50,1.90,1.87,2.05,2.00,1.29,6.00,11.50
362,E0,06/05/2018,Chelsea,Liverpool,1,0,H,1,0,H,...,2.13,22,-0.25,1.99,1.93,1.98,1.93,2.24,3.61,3.37
373,E0,13/05/2018,Liverpool,Brighton,4,0,H,2,0,H,...,2.86,21,-2.00,1.95,1.88,2.04,1.97,1.22,7.12,14.03

###### Liverpool wins

In [38]:
LivWins=data_file_pd.loc[((data_file_pd["HomeTeam"]=="Liverpool") & (data_file_pd["FTR"]=="H")) | ((data_file_pd["AwayTeam"]=="Liverpool") & (data_file_pd["FTR"]=="A") )]
LivWins

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
13,E0,19/08/2017,Liverpool,Crystal Palace,1,0,H,0,0,D,...,2.40,17,-1.50,2.14,2.07,1.85,1.82,1.39,5.31,9.00
27,E0,27/08/2017,Liverpool,Arsenal,4,0,H,2,0,H,...,2.38,16,-0.25,1.89,1.86,2.07,2.03,2.21,3.67,3.25
52,E0,23/09/2017,Leicester,Liverpool,2,3,A,1,2,A,...,2.18,17,0.75,1.82,1.78,2.16,2.11,4.40,4.18,1.81
93,E0,28/10/2017,Liverpool,Huddersfield,3,0,H,0,0,D,...,2.61,20,-2.00,2.26,2.16,1.79,1.73,1.25,6.70,14.00
105,E0,04/11/2017,West Ham,Liverpool,1,4,A,0,2,A,...,2.28,20,1.00,1.84,1.79,2.16,2.08,6.29,4.68,1.54
115,E0,18/11/2017,Liverpool,Southampton,3,0,H,2,0,H,...,2.24,19,-1.25,1.92,1.87,2.05,2.00,1.42,5.07,8.47
139,E0,29/11/2017,Stoke,Liverpool,0,3,A,0,1,A,...,2.38,19,1.00,2.07,2.02,1.88,1.85,6.21,4.58,1.56
141,E0,02/12/2017,Brighton,Liverpool,1,5,A,0,2,A,...,2.05,20,1.00,2.13,2.09,1.84,1.80,7.25,4.39,1.53
177,E0,17/12/2017,Bournemouth,Liverpool,0,4,A,0,3,A,...,2.41,21,1.00,2.13,2.08,1.84,1.80,7.35,5.25,1.44
193,E0,26/12/2017,Liverpool,Swansea,5,0,H,1,0,H,...,2.92,20,-2.25,2.02,1.97,1.95,1.90,1.14,10.50,21.00
203,E0,30/12/2017,Liverpool,Leicester,2,1,H,0,1,A,...,2.93,20,-1.75,2.11,2.03,1.87,1.83,1.27,7.10,11.00
210,E0,01/01/2018,Burnley,Liverpool,1,2,A,0,0,D,...,2.02,20,1.00,2.08,2.04,1.87,1.82,6.60,3.80,1.65
228,E0,14/01/2018,Liverpool,Man City,4,3,H,1,1,D,...,2.51,19,0.25,1.90,1.87,2.06,1.99,3.22,3.62,2.31
240,E0,30/01/2018,Huddersfield,Liverpool,0,3,A,0,2,A,...,2.20,20,1.50,2.02,1.96,1.95,1.90,10.95,5.49,1.34
268,E0,11/02/2018,Southampton,Liverpool,0,2,A,0,2,A,...,2.18,21,0.75,1.91,1.86,2.06,2.00,5.18,4.05,1.72
274,E0,24/02/2018,Liverpool,West Ham,4,1,H,1,0,H,...,2.79,21,-1.75,1.86,1.81,2.13,2.06,1.24,7.00,14.00
282,E0,03/03/2018,Liverpool,Newcastle,2,0,H,1,0,H,...,2.86,22,-2.00,2.04,1.96,1.97,1.90,1.20,7.80,16.00
302,E0,17/03/2018,Liverpool,Watford,5,0,H,2,0,H,...,2.89,22,-2.00,1.90,1.84,2.11,2.03,1.17,9.00,18.45
305,E0,31/03/2018,Crystal Palace,Liverpool,1,2,A,1,0,H,...,2.40,19,1.25,1.90,1.78,2.20,2.11,7.00,4.70,1.51
327,E0,14/04/2018,Liverpool,Bournemouth,3,0,H,1,0,H,...,3.02,19,-1.75,1.86,1.80,2.15,2.08,1.24,7.30,13.50
373,E0,13/05/2018,Liverpool,Brighton,4,0,H,2,0,H,...,2.86,21,-2.00,1.95,1.88,2.04,1.97,1.22,7.12,14.03

###### Liverpool odds : BET 365

In [44]:
LivOddsBet365Home=LivOddsBet365.loc[LivOddsBet365["FTR"]=="H"]
LivOddsBet365Home

      HomeTeam        AwayTeam FTR  B365H  B365D  B365A
13   Liverpool  Crystal Palace   H   1.36   5.25   9.50
27   Liverpool         Arsenal   H   2.15   3.70   3.50
93   Liverpool    Huddersfield   H   1.25   6.75  13.00
115  Liverpool     Southampton   H   1.39   5.00   9.00
193  Liverpool         Swansea   H   1.16   9.00  19.00
203  Liverpool       Leicester   H   1.30   6.00  11.00
228  Liverpool        Man City   H   3.10   3.75   2.29
274  Liverpool        West Ham   H   1.22   7.50  13.00
282  Liverpool       Newcastle   H   1.22   7.00  15.00
302  Liverpool         Watford   H   1.19   8.00  15.00
327  Liverpool     Bournemouth   H   1.25   7.00  12.00
373  Liverpool        Brighton   H   1.19   8.00  15.00

In [45]:
LivOddsBet365Away=LivOddsBet365.loc[LivOddsBet365["FTR"]=="A"]
LivOddsBet365Away

           HomeTeam   AwayTeam FTR  B365H  B365D  B365A
52        Leicester  Liverpool   A   4.10   3.90   1.91
105        West Ham  Liverpool   A   5.25   4.33   1.66
139           Stoke  Liverpool   A   6.50   4.50   1.55
141        Brighton  Liverpool   A   7.50   4.50   1.50
177     Bournemouth  Liverpool   A   6.50   4.50   1.53
210         Burnley  Liverpool   A   7.50   4.50   1.50
240    Huddersfield  Liverpool   A  12.00   5.75   1.30
268     Southampton  Liverpool   A   4.20   3.79   1.80
305  Crystal Palace  Liverpool   A   7.00   4.33   1.44

In [46]:
LivOddsBet365Home=LivOddsBet365.loc[LivOddsBet365["FTR"]=="H"]
totalHome=LivOddsBet365Home["B365H"].sum()
LivOddsBet365Away=LivOddsBet365.loc[LivOddsBet365["FTR"]=="A"]
totalAway=LivOddsBet365Away["B365A"].sum()
TotalOdds=totalHome+totalAway
print("Total season odds : ",TotalOdds)

Total season odds :  31.97

In [47]:
BetValue=1000
Savings=BetValue*38
Profit=BetValue*TotalOdds-Savings
print("bet value : ", BetValue)
print("Full season has 38 matches : ", Savings)
print("The profit of last on liverpool is : ", Profit)

bet value :  1000
Full season has 38 matches :  38000
The profit of last on liverpool is :  -6030.0