In [30]:
import numpy as np
import pandas as pd

In [31]:
data_file_pd=pd.read_csv("PL18_19.csv")

In [32]:
data_file.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,10/08/2018,Man United,Leicester,2,1,H,1,0,H,...,1.79,17,-0.75,1.75,1.70,2.29,2.21,1.55,4.07,7.69
1,E0,11/08/2018,Bournemouth,Cardiff,2,0,H,1,0,H,...,1.83,20,-0.75,2.20,2.13,1.80,1.75,1.88,3.61,4.70
2,E0,11/08/2018,Fulham,Crystal Palace,0,2,A,0,1,A,...,1.87,22,-0.25,2.18,2.11,1.81,1.77,2.62,3.38,2.90
3,E0,11/08/2018,Huddersfield,Chelsea,0,3,A,0,2,A,...,1.84,23,1.00,1.84,1.80,2.13,2.06,7.24,3.95,1.58
4,E0,11/08/2018,Newcastle,Tottenham,1,2,A,1,2,A,...,1.81,20,0.25,2.20,2.12,1.80,1.76,4.74,3.53,1.89

In [33]:
data_file.iloc[0]

Div                 E0
Date        10/08/2018
HomeTeam    Man United
AwayTeam     Leicester
FTHG                 2
               ...
BbMxAHA           2.29
BbAvAHA           2.21
PSCH              1.55
PSCD              4.07
PSCA              7.69
Name: 0, Length: 62, dtype: object

In [35]:
data_file_pd.loc[data_file_pd['HomeTeam']]=="Liverpool"

KeyError: "None of [Index(['Man United', 'Bournemouth', 'Fulham', 'Huddersfield', 'Newcastle',\n       'Watford', 'Wolves', 'Arsenal', 'Liverpool', 'Southampton',\n       ...\n       'Brighton', 'Burnley', 'Crystal Palace', 'Fulham', 'Leicester',\n       'Liverpool', 'Man United', 'Southampton', 'Tottenham', 'Watford'],\n      dtype='object', length=380)] are in the [index]"